2025-04-04T20:22:36.421+0000 [INFO] Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iis_etl.processing.transform scheduled__2025-04-04T20:13:24.294473+00:00 [queued]>
2025-04-04T20:22:36.428+0000 [INFO] Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iis_etl.processing.transform scheduled__2025-04-04T20:13:24.294473+00:00 [queued]>
2025-04-04T20:22:36.428+0000 [INFO] Starting attempt 3 of 4
2025-04-04T20:22:36.441+0000 [INFO] Executing <Task(PythonOperator): processing.transform> on 2025-04-04 20:13:24.294473+00:00
2025-04-04T20:22:36.446+0000 [INFO] Started process 63 to run task
2025-04-04T20:22:36.449+0000 [INFO] Running: ['airflow', 'tasks', 'run', 'iis_etl', 'processing.transform', 'scheduled__2025-04-04T20:13:24.294473+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/iis_etl.py', '--cfg-path', '/tmp/tmpfvp6g0k8']
2025-04-04T20:22:36.451+0000 [INFO] Job 8: Subtask processing.transform
2025-04-04T20:22:36.710+0000 [INFO] Running <TaskInstance: iis_etl.processing.transform scheduled__2025-04-04T20:13:24.294473+00:00 [running]> on host b8e5693c89ab
2025-04-04T20:22:36.753+0000 [INFO] Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iis_etl' AIRFLOW_CTX_TASK_ID='processing.transform' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T20:13:24.294473+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T20:13:24.294473+00:00'
2025-04-04T20:22:36.788+0000 [ERROR] Transform failed: unsupported operand type(s) for +: 'DatetimeArray' and 'str'
Traceback (most recent call last):
  File "/opt/airflow/dags/iis_etl.py", line 615, in transform
    df = transform_log_data(df)
  File "/opt/airflow/dags/iis_etl.py", line 122, in transform_log_data
    df['timestamp'] = pd.to_datetime(df['date'] + ' ' + df['time'], errors='coerce').dt.tz_localize('UTC')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 92, in __add__
    return self._arith_method(other, operator.add)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 218, in arithmetic_op
    res_values = op(left, right)
TypeError: unsupported operand type(s) for +: 'DatetimeArray' and 'str'
2025-04-04T20:22:36.790+0000 [ERROR] Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/iis_etl.py", line 615, in transform
    df = transform_log_data(df)
  File "/opt/airflow/dags/iis_etl.py", line 122, in transform_log_data
    df['timestamp'] = pd.to_datetime(df['date'] + ' ' + df['time'], errors='coerce').dt.tz_localize('UTC')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 92, in __add__
    return self._arith_method(other, operator.add)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 218, in arithmetic_op
    res_values = op(left, right)
TypeError: unsupported operand type(s) for +: 'DatetimeArray' and 'str'
2025-04-04T20:22:36.794+0000 [INFO] Marking task as UP_FOR_RETRY. dag_id=iis_etl, task_id=processing.transform, execution_date=20250404T201324, start_date=20250404T202236, end_date=20250404T202236
2025-04-04T20:22:36.800+0000 [ERROR] Failed to execute job 8 for task processing.transform (unsupported operand type(s) for +: 'DatetimeArray' and 'str'; 63)
2025-04-04T20:22:36.806+0000 [INFO] Task exited with return code 1
2025-04-04T20:22:36.907+0000 [INFO] 0 downstream tasks scheduled from follow-on schedule check
