2025-04-04T20:23:40.982+0000 [INFO] Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iis_etl.processing.load_dimensions manual__2025-04-04T20:18:25.100161+00:00 [queued]>
2025-04-04T20:23:40.988+0000 [INFO] Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iis_etl.processing.load_dimensions manual__2025-04-04T20:18:25.100161+00:00 [queued]>
2025-04-04T20:23:40.988+0000 [INFO] Starting attempt 1 of 4
2025-04-04T20:23:40.995+0000 [INFO] Executing <Task(PythonOperator): processing.load_dimensions> on 2025-04-04 20:18:25.100161+00:00
2025-04-04T20:23:40.997+0000 [INFO] Started process 81 to run task
2025-04-04T20:23:40.999+0000 [INFO] Running: ['airflow', 'tasks', 'run', 'iis_etl', 'processing.load_dimensions', 'manual__2025-04-04T20:18:25.100161+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/iis_etl.py', '--cfg-path', '/tmp/tmpbbxl7l7c']
2025-04-04T20:23:41.000+0000 [INFO] Job 14: Subtask processing.load_dimensions
2025-04-04T20:23:41.113+0000 [INFO] Running <TaskInstance: iis_etl.processing.load_dimensions manual__2025-04-04T20:18:25.100161+00:00 [running]> on host b8e5693c89ab
2025-04-04T20:23:41.152+0000 [INFO] Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iis_etl' AIRFLOW_CTX_TASK_ID='processing.load_dimensions' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T20:18:25.100161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T20:18:25.100161+00:00'
2025-04-04T20:23:41.199+0000 [INFO] Using connection ID 'postgres_iis' for task execution.
2025-04-04T20:23:41.237+0000 [ERROR] Dimension loading failed: (psycopg2.errors.UndefinedColumn) column "day_of_week" of relation "dim_time" does not exist
LINE 3:                 (timestamp, hour, time_period, day_of_week, ...
                                                       ^

[SQL: 
                INSERT INTO dim_time 
                (timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend)
                SELECT timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend
                FROM temp_time
                ON CONFLICT (timestamp) DO NOTHING
            ]
(Background on this error at: https://sqlalche.me/e/14/f405)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "day_of_week" of relation "dim_time" does not exist
LINE 3:                 (timestamp, hour, time_period, day_of_week, ...
                                                       ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/iis_etl.py", line 423, in load_dimensions
    """)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    future=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1676, in _exec_driver_sql
    distilled_parameters,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "day_of_week" of relation "dim_time" does not exist
LINE 3:                 (timestamp, hour, time_period, day_of_week, ...
                                                       ^

[SQL: 
                INSERT INTO dim_time 
                (timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend)
                SELECT timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend
                FROM temp_time
                ON CONFLICT (timestamp) DO NOTHING
            ]
(Background on this error at: https://sqlalche.me/e/14/f405)
2025-04-04T20:23:41.241+0000 [ERROR] Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "day_of_week" of relation "dim_time" does not exist
LINE 3:                 (timestamp, hour, time_period, day_of_week, ...
                                                       ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/iis_etl.py", line 423, in load_dimensions
    """)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    future=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1676, in _exec_driver_sql
    distilled_parameters,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "day_of_week" of relation "dim_time" does not exist
LINE 3:                 (timestamp, hour, time_period, day_of_week, ...
                                                       ^

[SQL: 
                INSERT INTO dim_time 
                (timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend)
                SELECT timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend
                FROM temp_time
                ON CONFLICT (timestamp) DO NOTHING
            ]
(Background on this error at: https://sqlalche.me/e/14/f405)
2025-04-04T20:23:41.245+0000 [INFO] Marking task as UP_FOR_RETRY. dag_id=iis_etl, task_id=processing.load_dimensions, execution_date=20250404T201825, start_date=20250404T202340, end_date=20250404T202341
2025-04-04T20:23:41.250+0000 [ERROR] Failed to execute job 14 for task processing.load_dimensions ((psycopg2.errors.UndefinedColumn) column "day_of_week" of relation "dim_time" does not exist
LINE 3:                 (timestamp, hour, time_period, day_of_week, ...
                                                       ^

[SQL: 
                INSERT INTO dim_time 
                (timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend)
                SELECT timestamp, hour, time_period, day_of_week, date, month, quarter, year, is_weekend
                FROM temp_time
                ON CONFLICT (timestamp) DO NOTHING
            ]
(Background on this error at: https://sqlalche.me/e/14/f405); 81)
2025-04-04T20:23:41.263+0000 [INFO] Task exited with return code 1
2025-04-04T20:23:41.370+0000 [INFO] 0 downstream tasks scheduled from follow-on schedule check
